/**
 * NETWORK
 */
export const NETWORK_CONNECTION_CHANGE = 'NETWORK_CONNECTION_CHANGE';

/**
 * PHOTO
 */
export const FETCH_PHOTO_SUCCESSFUL = 'FETCH_PHOTO_SUCCESSFUL';
export const FETCH_PHOTO_FAILED = 'FETCH_PHOTO_FAILED';
